project:
  name: quickstart-taskcat-ci
  owner: quickstart-eng@amazon.com
  shorten_stack_name: true
  package_lambda: true
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  template: templates/taskcat-ci-entrypoint.template.yaml
  regions:
    - af-south-1
    - ap-east-1
    - ap-northeast-1
    - ap-northeast-2
    - ap-northeast-3
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ap-southeast-3
    - ca-central-1
    - eu-central-1
    - eu-north-1
    - eu-south-1
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - me-south-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - us-gov-east-1
    - us-gov-west-1
    - cn-north-1
    - cn-northwest-1
  parameters:
    GitHubUsername: --override--
    GitHubOAuthToken: --override--
    GitHubOwner: --override--
    GitHubRepoName: --override--
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
tests:
  taskcat-ci:
    regions:
      - us-west-2
