version: 0.2
env:
  variables:
    # Definining CloudFormation Teamplate and Ruleset as variables - part of the code repo
    CF_TEMPLATE: "templates/SampleProject.yaml"
    CF_ORG_RULESET:  "templates/cfn_guard_ruleset_example"
phases:
  install:
    commands:
      - yum update -y
      - PYTHON=python2 amazon-linux-extras enable rust1
      - yum clean metadata
      - yum install rust cargo -y
      - yum install git -y
  build:
    commands:
       - echo "Pull GA release from github"
       - echo "More info https://github.com/aws-cloudformation/cloudformation-guard/releases"
       - wget https://github.com/aws-cloudformation/cloudformation-guard/releases/download/1.0.0/cfn-guard-linux-1.0.0.tar.gz
       - echo "Extract cfn-guard"
       - tar xvf cfn-guard-linux-1.0.0.tar.gz .
  post_build:
    commands:
       - echo "Validate CloudFormation template with cfn-guard tool"
       - echo "More information https://github.com/aws-cloudformation/cloudformation-guard/blob/master/cfn-guard/README.md"
       - cfn-guard-linux/cfn-guard check --rule_set $CF_ORG_RULESET --template $CF_TEMPLATE --strict-checks
#artifacts:
#  files:
#    - cfn_template_file_example.yaml
#  name: guard_templates