version: 0.2
env:
  variables:
    # Definining CloudFormation Template and Ruleset as variables - part of the code repo
    CF_ORG_RULESET:  "cfn_guard_ruleset"
phases:
  install:
    commands:
      - echo "Pull GA release from github"
      - echo "More info https://github.com/aws-cloudformation/cloudformation-guard/releases"
      - wget https://github.com/aws-cloudformation/cloudformation-guard/releases/download/1.0.0/cfn-guard-linux-1.0.0.tar.gz
  build:
    commands:
      # TODO: Allow guard ruleset to be specified in the repo
      - "curl -sL https://github.com/elerch/quickstart-taskcat-ci/raw/iaccompliance/assets/cfn_guard_ruleset > cfn_guard_ruleset"
      - echo "Extract cfn-guard"
      - tar xvf cfn-guard-linux-1.0.0.tar.gz .
  post_build:
    commands:
      - echo "Validate CloudFormation template with cfn-guard tool"
      - echo "More information https://github.com/aws-cloudformation/cloudformation-guard/blob/master/cfn-guard/README.md"
      - 'for file in infra/*.yaml; do echo "$file"; cfn-guard-linux/cfn-guard check --rule_set $CF_ORG_RULESET --template "$file" --strict-checks; done'
