version: 0.2
env:
  variables:
    # Definining CloudFormation Template and Ruleset as variables - part of the code repo
    CF_ORG_RULESET:  "cfn_guard_ruleset"
phases:
  install:
    commands:
      - echo "Pull GA release from github"
      - echo "More info https://github.com/aws-cloudformation/cloudformation-guard/releases"
      # TODO: Allow guard ruleset to be specified in the repo
      - "curl -sL https://github.com/elerch/quickstart-taskcat-ci/raw/iaccompliance/assets/cfn_guard_ruleset > cfn_guard_ruleset"
      - "curl -sL https://github.com/elerch/quickstart-taskcat-ci/raw/iaccompliance/assets/cfn-guard-directory > cfn-guard-directory"
      - chmod 755 cfn-guard-directory
      - echo "Extract cfn-guard"
      - mkdir -p infra
      - cd infra
      - wget -q https://github.com/aws-cloudformation/cloudformation-guard/releases/download/1.0.0/cfn-guard-linux-1.0.0.tar.gz
      - tar xf cfn-guard-linux-1.0.0.tar.gz .
      - cd ..
  build:
    commands:
      - ./cfn-guard-directory infra
      - ./cfn-guard-directory templates # for CDK projects
