#!/bin/bash

templateloc=$1
shopt -s nullglob extglob
mkdir -p "$templateloc"
pushd "$templateloc" || exit 1
if [ -n "$(echo ./*.@(json|yml|yaml))" ]; then
  echo "linting: *.@(json|yml|yaml)"
  cfn-lint -r "$AWS_REGION" -- *.@(json|yml|yaml)
  rc=$?
  [ $rc -gt 0 ] && exit $rc
  echo "done"
else
  echo "no files to lint"
fi
popd || exit 1
